### ISSUE TITLE
Seat 5.x support

### ISSUE THREAD

**Issue by 5up41** [pyTonicis/seat-corp-mining-tax#4]
Hey there,
first of all thank you
and like the title implies: any chance to get SeAT 5 support?
I updated for whatever reason and then instantly remove the save points to roll back and now lack this very important part of our SeAT session ^^

Thank you in advance!

**Comment by pyTonicis** [comment]
Yes, working on it. In the next few days i will release it for seat v5.

**Comment by pyTonicis** [comment]
Version for seat v5 released :)
